apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "macvlan",
    "type": "macvlan",
    "mode": "bridge",
    "master": "eth1",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.0.0/24",
        "rangeStart": "10.0.0.201",
        "rangeEnd": "10.0.0.205",
        "routes": [
                  { "dst": "10.10.0.0/8" }
                  ],
                "gateway": "10.0.0.1"
      }
    }'
