apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "macvlan",
    "type": "macvlan",
    "mode": "bridge",
    "master": "eth1",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.1.0/24",
        "rangeStart": "10.0.1.201",
        "rangeEnd": "10.0.1.205",
        "routes": [
                  { "dst": "10.10.0.0/24" }
                  ],
                "gateway": "10.0.1.1" 
      }
    }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multus-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-multus-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-multus-test
      namespace: default
    spec:
      affinity: {}
      containers:
        - command:
            - sleep
            - infinity
          image: busybox
          imagePullPolicy: Always
          name: container-0
          resources: {}
#          securityContext:
#            privileged: true
