apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "ipvlan",
    "type": "vlan",
    "mode": "l2",
    "master": "eth1",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.0.0/24",
        "rangeStart": "10.0.0.201",
        "rangeEnd": "10.0.0.205",
        "routes": [
                  { "dst": "10.10.0.0/8" }
                  ],
                "gateway": "10.0.0.1"
      }
    }'
---
apiVersion: v1
kind: Pod
metadata:
  name: multus-test-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: busybox
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
