apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "macvlan",
    "type": "macvlan",
    "mode": "bridge",
    "master": "eth1",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.1.0/24",
        "rangeStart": "10.0.1.201",
        "rangeEnd": "10.0.1.205" 
      }
    }'
---
apiVersion: v1
kind: Pod
metadata:
  name: multus-test-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: busybox
#    securityContext:
#      capabilities:
#        add:
#        - NET_ADMIN
#        - NET_RAW
